#!/bin/bash
#

default_task_index=$1

echo ""
echo "=== Welcome to VASPRUN SERVER TEST ==="
echo ""
echo "Please input the task index you need to execute."
echo "[1] Run the lib benchmark."
echo "[2] Run the test calculation."
echo "[3] Report the test result."
echo "[0] Quit."
echo "Default: ${default_task_index}"
read -p '> ' task_index
if [ "${task_index}" != "1" ] && \
   [ "${task_index}" != "2" ] && \
   [ "${task_index}" != "3" ]; then 
  task_index=${default_task_index}
fi

case "${task_index}" in 
  "1")
    echo "[do] Benchmark..." 
    bash ./prog/exec_benchmark.sh
    ;;
  "2")
    echo "[do] Test calculation..." 
    bash ./prog/exec_submit_tests.sh
    ;;
  "3")
    echo "[do] Report test result..." 
    bash ./prog/exec_report_result.sh
    ;;
  "*")
    exit 1
esac
